-- 연도별 대장균 크기의 편차 구하기
SELECT E2.YEAR AS YEAR, 
    (E2.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA E1,
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) E2
WHERE YEAR(DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR, YEAR_DEV;