-- 업그레이드 된 아이템 구하기
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A JOIN
    (SELECT T.ITEM_ID
    FROM ITEM_TREE T JOIN ITEM_INFO I
    ON T.PARENT_ITEM_ID = I.ITEM_ID
    WHERE I.RARITY = 'RARE'
    ) AS B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC;