-- 조건에 맞는 사원 정보 조회하기
SELECT SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
    ) AS A JOIN HR_EMPLOYEES B
ON A.EMP_NO = B.EMP_NO;